In [1]:
import pandas as pd

In [2]:
"""initail data and stuff"""

divisions = {
    "AL-East":    ("BAL", "BOS", "NYA", "TBA", "TOR"),
    "AL-Central": ("CHA", "CLE", "DET", "KCA", "MIN"),
    "AL-West":    ("ANA", "HOU", "OAK", "SEA", "TEX"),

    "NL-East":    ("ATL", "MIA", "NYN", "PHI", "WAS"),
    "NL-Central": ("CHN", "CIN", "MIL", "PIT", "SLN"),
    "NL-West":    ("ARI", "COL", "LAN", "SDN", "SFN")
}

**PART 1 CODE**

In [3]:
"""PART 1 CODE (for 2014+)"""

rows = []

for season in range(2014, 2025):
    for division, teams in divisions.items():
        rows.append({
            "season": season,
            "league": "MLB",
            "division": division,
            "division_teams": teams
        })

division_df = pd.DataFrame(rows)
division_df.to_csv("mlb_divisions.csv", index=False)

**PART 2 CODE**

In [4]:
games_df = pd.read_csv("game_data_us_leagues.csv")

# Make one row per season/team/division
team_division_df = (
    division_df
    .explode("division_teams")
    .rename(columns={"division_teams": "team"})
)

# this is only the baseball games
mlb_games = games_df[
    (games_df["league"] == "MLB") &
    (games_df["season"].between(2014, 2024))
].copy()

In [5]:
# adding team 1 and team 2 division by merging with our mlb_divisions
mlb_games = mlb_games.merge(
    team_division_df[["season", "team", "division"]],
    left_on=["season", "team1"],
    right_on=["season", "team"],
    how="left"
)

mlb_games = (
    mlb_games
    .rename(columns={"division": "division1"})
    .drop(columns="team")
)

# adds team 2 div
mlb_games = mlb_games.merge(
    team_division_df[["season", "team", "division"]],
    left_on=["season", "team2"],
    right_on=["season", "team"],
    how="left"
)

mlb_games = (
    mlb_games
    .rename(columns={"division": "division2"})
    .drop(columns="team")
)

# season team1 team2 division1 division2

In [6]:
# FILTERING BY DIVISON
div_games = mlb_games[
    mlb_games["division1"] == mlb_games["division2"]
].copy()

div_games["division"] = div_games["division1"]

div_games = div_games.drop(columns=["division1", "division2"])
#div_games.head()

In [7]:
# go game by game and figure out the winner
def get_winner(row):
    if row["score1"] > row["score2"]:
        return row["team1"]
    elif row["score2"] > row["score1"]:
        return row["team2"]
    else:
        return None


div_games["winner"] = div_games.apply(
    get_winner,
    axis=1
)

In [8]:
# pairs need to have same ordering so wehn we do pd.group we dont double count
teams = div_games[["team1", "team2"]]

div_games["team1"] = teams.min(axis=1)
div_games["team2"] = teams.max(axis=1)

In [9]:
# mark whoever winner in a div game
div_games["win1"] = (
    div_games["winner"] == div_games["team1"]
).astype(int)

div_games["win2"] = (
    div_games["winner"] == div_games["team2"]
).astype(int)

In [10]:
# compute the series games
series_df = (
    div_games
    .groupby(
        ["season", "division", "team1", "team2"],
        as_index=False
    )
    .agg(
        wins1=("win1", "sum"),
        wins2=("win2", "sum")
    )
)

In [11]:
# determine the full series winner
def get_series_result(row):
    if row["wins1"] > row["wins2"]:
        return 1
    elif row["wins2"] > row["wins1"]:
        return -1
    else:
        return 0


series_df["result"] = series_df.apply(
    get_series_result,
    axis=1
)

# adds the other column we need to specifiy that this is mlb
series_df.insert(
    1,
    "league",
    "MLB"
)

In [12]:
series_df = series_df[
    [
        "season",
        "league",
        "division",
        "team1",
        "team2",
        "result",
        "wins1",
        "wins2"
    ]
]

In [19]:
series_df.tail(n=60)

     season league    division team1 team2  result  wins1  wins2
600    2024    MLB  AL-Central   CHA   CLE      -1      5      8
601    2024    MLB  AL-Central   CHA   DET      -1      3     10
602    2024    MLB  AL-Central   CHA   KCA      -1      1     12
603    2024    MLB  AL-Central   CHA   MIN      -1      1     12
604    2024    MLB  AL-Central   CLE   DET       1      7      6
605    2024    MLB  AL-Central   CLE   KCA      -1      5      8
606    2024    MLB  AL-Central   CLE   MIN       1     10      3
607    2024    MLB  AL-Central   DET   KCA      -1      6      7
608    2024    MLB  AL-Central   DET   MIN      -1      6      7
609    2024    MLB  AL-Central   KCA   MIN      -1      6      7
610    2024    MLB     AL-East   BAL   BOS       1      8      5
611    2024    MLB     AL-East   BAL   NYA       1      8      5
612    2024    MLB     AL-East   BAL   TBA       1      9      4
613    2024    MLB     AL-East   BAL   TOR       1      7      6
614    2024    MLB     AL-East   BOS   NYA      -1      6      7
615    2024    MLB     AL-East   BOS   TBA      -1      6      7
616    2024    MLB     AL-East   BOS   TOR       1      8      5
617    2024    MLB     AL-East   NYA   TBA       1      7      6
618    2024    MLB     AL-East   NYA   TOR       1      7      6
619    2024    MLB     AL-East   TBA   TOR       1      9      4
620    2024    MLB     AL-West   ANA   HOU      -1      4      9
621    2024    MLB     AL-West   ANA   OAK      -1      5      8
622    2024    MLB     AL-West   ANA   SEA       1      8      5
623    2024    MLB     AL-West   ANA   TEX      -1      4      9
624    2024    MLB     AL-West   HOU   OAK       1      8      5
625    2024    MLB     AL-West   HOU   SEA      -1      5      8
626    2024    MLB     AL-West   HOU   TEX       1      7      6
627    2024    MLB     AL-West   OAK   SEA      -1      4      9
628    2024    MLB     AL-West   OAK   TEX      -1      6      7
629    2024    MLB     AL-West   SEA   TEX       1     10      3
630    2024    MLB  NL-Central   CHN   CIN      -1      5      8
631    2024    MLB  NL-Central   CHN   MIL      -1      5      8
632    2024    MLB  NL-Central   CHN   PIT       1      7      6
633    2024    MLB  NL-Central   CHN   SLN      -1      6      7
634    2024    MLB  NL-Central   CIN   MIL      -1      4      9
635    2024    MLB  NL-Central   CIN   PIT      -1      5      8
636    2024    MLB  NL-Central   CIN   SLN       1      7      6
637    2024    MLB  NL-Central   MIL   PIT       1      7      6
638    2024    MLB  NL-Central   MIL   SLN       1      8      5
639    2024    MLB  NL-Central   PIT   SLN      -1      5      8
640    2024    MLB     NL-East   ATL   MIA       1      9      4
641    2024    MLB     NL-East   ATL   NYN       1      7      6
642    2024    MLB     NL-East   ATL   PHI       1      7      6
643    2024    MLB     NL-East   ATL   WAS      -1      5      8
644    2024    MLB     NL-East   MIA   NYN      -1      6      7
645    2024    MLB     NL-East   MIA   PHI      -1      6      7
646    2024    MLB     NL-East   MIA   WAS      -1      2     11
647    2024    MLB     NL-East   NYN   PHI      -1      6      7
648    2024    MLB     NL-East   NYN   WAS       1     11      2
649    2024    MLB     NL-East   PHI   WAS       1      9      4
650    2024    MLB     NL-West   ARI   COL       1      9      4
651    2024    MLB     NL-West   ARI   LAN      -1      6      7
652    2024    MLB     NL-West   ARI   SDN      -1      6      7
653    2024    MLB     NL-West   ARI   SFN       1      7      6
654    2024    MLB     NL-West   COL   LAN      -1      3     10
655    2024    MLB     NL-West   COL   SDN       1      8      5
656    2024    MLB     NL-West   COL   SFN      -1      3     10
657    2024    MLB     NL-West   LAN   SDN      -1      5      8
658    2024    MLB     NL-West   LAN   SFN       1      9      4
659    2024    MLB     NL-West   SDN   SFN       1      7      6

In [25]:
df2 = series_df.copy()
df2['gamesum'] = df2['wins1'] + df2['wins2']
df2[(df2['gamesum'] != 13) & (df2['gamesum'] != 19) & (df2['gamesum'] != 10)]

     season league    division team1 team2  result  wins1  wins2  gamesum
64     2015    MLB  AL-Central   CLE   DET      -1      7     11       18
124    2016    MLB  AL-Central   CLE   DET       1     14      4       18
152    2016    MLB  NL-Central   CHN   PIT       1     14      4       18
160    2016    MLB     NL-East   ATL   MIA       1     11      7       18
271    2018    MLB  NL-Central   CHN   MIL       1     11      9       20
294    2018    MLB     NL-West   COL   LAN      -1      7     13       20
301    2019    MLB  AL-Central   CHA   DET       1     12      6       18